/*
  Warnings:

  - The values [MANAGE_SERVER,MANAGE_ROLES,MANAGE_CHANNELS,CREATE_INVITE,KICK_MEMBERS,BAN_MEMBERS,TIMEOUT_MEMBERS,MANAGE_MESSAGES,MANAGE_THREADS,MANAGE_WEBHOOKS,MANAGE_EMOJIS,VIEW_AUDIT_LOG,MENTION_EVERYONE] on the enum `ServerPermission` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ServerPermission_new" AS ENUM ('SERVER_VIEW', 'SERVER_UPDATE', 'SERVER_DELETE', 'INVITE_CREATE', 'INVITE_DELETE', 'CATEGORY_CREATE', 'CATEGORY_UPDATE', 'CATEGORY_DELETE', 'CHANNEL_VIEW', 'CHANNEL_CREATE', 'CHANNEL_UPDATE', 'CHANNEL_DELETE', 'MESSAGE_SEND', 'MESSAGE_UPDATE', 'MESSAGE_DELETE', 'MESSAGE_PIN', 'MEMBER_INVITE', 'MEMBER_KICK', 'MEMBER_BAN', 'MEMBER_TIMEOUT', 'ROLE_CREATE', 'ROLE_UPDATE', 'ROLE_DELETE', 'ROLE_ASSIGN', 'WEBHOOK_MANAGE', 'EMOJI_MANAGE', 'AUDIT_LOG_VIEW', 'ADMINISTRATOR');
ALTER TABLE "ServerRolePermission" ALTER COLUMN "permission" TYPE "ServerPermission_new" USING ("permission"::text::"ServerPermission_new");
ALTER TYPE "ServerPermission" RENAME TO "ServerPermission_old";
ALTER TYPE "ServerPermission_new" RENAME TO "ServerPermission";
DROP TYPE "public"."ServerPermission_old";
COMMIT;
