export enum AuthorizationAuditAction {
  ASSIGN_PERMISSION = 'ASSIGN_PERMISSION',

  ASSIGN_PERMISSIONS = 'ASSIGN_PERMISSIONS',

  REMOVE_PERMISSION = 'REMOVE_PERMISSION',

  REPLACE_PERMISSIONS = 'REPLACE_PERMISSIONS',

  ASSIGN_ROLE = 'ASSIGN_ROLE',

  REMOVE_ROLE = 'REMOVE_ROLE',

  REPLACE_ROLES = 'REPLACE_ROLES',
}
