import {
  IsNotEmpty,
  IsString,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

import { ANONYMOUS_MAX_MESSAGE_LENGTH } from '../../constants/anonymous-chat.constants';

export class SendAnonymousMessageRequest {
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  sessionId!: string;

  @ApiProperty({
    description:
      'Unique idempotency key generated by the client (UUID / ULID) used to deduplicate replays.',
  })
  @IsUUID()
  messageId!: string;

  @ApiProperty()
  @IsString()
  @MinLength(1)
  @MaxLength(ANONYMOUS_MAX_MESSAGE_LENGTH)
  content!: string;
}
