export const COMMUNITY_DEFAULT_PAGE_SIZE = 20;

export const COMMUNITY_MAX_PAGE_SIZE = 100;

export const COMMUNITY_FEED_DEFAULT_PAGE_SIZE = 20;

export const COMMUNITY_FEED_MAX_PAGE_SIZE = 50;

export const COMMUNITY_COMMENT_DEFAULT_PAGE_SIZE = 50;

export const COMMUNITY_COMMENT_MAX_PAGE_SIZE = 100;

export const COMMUNITY_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export const COMMUNITY_SLUG_MAX_LENGTH = 60;

export const COMMUNITY_NAME_MAX_LENGTH = 120;

export const COMMUNITY_DESCRIPTION_MAX_LENGTH = 500;

export const COMMUNITY_POST_TITLE_MAX_LENGTH = 200;

export const COMMUNITY_POST_CONTENT_MAX_LENGTH = 20_000;

export const COMMUNITY_COMMENT_CONTENT_MAX_LENGTH = 4_000;
