export enum ServerTemplateType {
  CLASSROOM = 'CLASSROOM',
  SCHOOL_CLUB = 'SCHOOL_CLUB',
  CODING = 'CODING',
  UNIVERSITY = 'UNIVERSITY',
  COMPANY = 'COMPANY',
  STUDY_GROUP = 'STUDY_GROUP',
  GAMING = 'GAMING',
  CUSTOM = 'CUSTOM',
}
