export enum NexusErrorCode {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  // Channel
  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  CHANNEL_ACCESS_DENIED = 'CHANNEL_ACCESS_DENIED',

  // Messages
  MESSAGE_EMPTY = 'MESSAGE_EMPTY',
  MESSAGE_TOO_LONG = 'MESSAGE_TOO_LONG',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_EDIT_FORBIDDEN = 'MESSAGE_EDIT_FORBIDDEN',
  MESSAGE_DELETE_FORBIDDEN = 'MESSAGE_DELETE_FORBIDDEN',
  MESSAGE_PIN_FORBIDDEN = 'MESSAGE_PIN_FORBIDDEN',

  // Reactions
  REACTION_ALREADY_EXISTS = 'REACTION_ALREADY_EXISTS',
  REACTION_NOT_FOUND = 'REACTION_NOT_FOUND',
  REACTION_FORBIDDEN = 'REACTION_FORBIDDEN',
}
