export const AuditActions = {
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_DELETED: 'ROLE_DELETED',

  PERMISSION_ASSIGNED: 'PERMISSION_ASSIGNED',
  PERMISSION_REMOVED: 'PERMISSION_REMOVED',
  PERMISSION_CREATED: 'PERMISSION_CREATED',
  PERMISSION_DELETED: 'PERMISSION_DELETED',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REFRESH: 'REFRESH',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
} as const;
